# Generated by Django 6.1 on 2026-08-24 06:04

import app.accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_birth_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_number_encrypted', models.TextField(blank=True, editable=False)),
                ('id_number_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=False, editable=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('is_active', False)), _connector='OR'), name='user_is_active_matches_status', violation_error_message='is_active is derived from status and cannot be set directly.')],
            },
            managers=[
                ('objects', app.accounts.models.UserManager()),
            ],
        ),
    ]
