# Generated by Django 6.1 on 2026-08-24 08:46

import app.common.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, help_text='Stored as +27 and nine digits, whatever form it was given in.', max_length=16, validators=[app.common.validators.validate_sa_mobile_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('pending_payment', 'Pending payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), condition=models.Q(('nickname', ''), _negated=True), name='user_nickname_unique_ci', violation_error_message='That nickname is already taken.'),
        ),
    ]
