# Generated by Django 6.1 on 2026-08-26 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_portable_uniqueness_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityNumberDisclosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(help_text='Why the number had to be read. Recorded, and never blank.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='identity_disclosures', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_numbers_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'identity number disclosure',
                'verbose_name_plural': 'identity number disclosures',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['member', '-created_at'], name='idnum_disclosure_member_idx')],
            },
        ),
    ]
