# Generated by Django 6.1 on 2026-08-27 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('storefront', models.CharField(choices=[('club', 'Cultivators Collective'), ('market', 'Produce market')], db_index=True, help_text='Which storefront this person administers.', max_length=16)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('appointed_by', models.ForeignKey(blank=True, help_text='The platform operator who granted this. Blank once they are erased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_appointments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'storefront administrator',
                'verbose_name_plural': 'storefront administrators',
                'ordering': ('storefront', 'appointed_at'),
                'constraints': [models.UniqueConstraint(fields=('user', 'storefront'), name='storefront_staff_once_per_storefront', violation_error_message='This person already administers that storefront.'), models.CheckConstraint(condition=models.Q(('storefront__in', ['club', 'market'])), name='storefront_staff_storefront_is_known', violation_error_message='That is not a storefront this platform serves.')],
            },
        ),
    ]
