# Generated by Django 6.1 on 2026-09-01 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('login_code', 'Sign-in code'), ('payment_link', 'Membership payment link'), ('membership_suspended', 'Membership suspended'), ('access_revoked', 'Platform access revoked')], help_text='Which of the platform’s emails this was.', max_length=32)),
                ('storefront', models.CharField(choices=[('club', 'Cultivators Collective'), ('market', 'Produce market')], db_index=True, help_text='Whose letterhead it carried, and whose server it left by.', max_length=16)),
                ('subject', models.CharField(help_text='The subject line as sent. The body is deliberately not kept.', max_length=255)),
                ('trigger', models.CharField(choices=[('system', 'The platform itself'), ('member', 'The recipient'), ('operator', 'An operator')], db_index=True, help_text='Whether the platform, the recipient, or an operator caused it.', max_length=16)),
                ('send_status', models.CharField(choices=[('queued', 'Not handed over yet'), ('sent', 'Accepted by the mail server'), ('failed', 'Refused by the mail server')], default='queued', max_length=16)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the mail server accepted it. Not when it arrived.', null=True)),
                ('send_error', models.TextField(blank=True, help_text='Why the mail server refused it, as it was reported.')),
                ('delivery_status', models.CharField(choices=[('unknown', 'Not reported'), ('delivered', 'Delivered'), ('deferred', 'Delayed, still trying'), ('bounced', 'Bounced'), ('rejected', 'Rejected'), ('complained', 'Reported as spam')], db_index=True, default='unknown', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the delivery outcome was reported — an arrival or a bounce. Empty on an SMTP-only deployment, which is told neither.', null=True)),
                ('delivery_detail', models.TextField(blank=True, help_text='What the provider said, e.g. a bounce reason.')),
                ('read_status', models.CharField(choices=[('not_tracked', 'Not tracked'), ('unopened', 'Tracked, not opened yet'), ('read', 'Opened')], db_index=True, default='not_tracked', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='The mail provider’s id for this message, where it gives one.', max_length=255)),
                ('recipient', models.ForeignKey(help_text='The account it was addressed to. The address is read off it.', on_delete=django.db.models.deletion.CASCADE, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, help_text='The person who caused it, where one can be named. Blank for a system send and for a request that was not signed in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email sent',
                'verbose_name_plural': 'emails sent',
                'ordering': ('-queued_at',),
                'indexes': [models.Index(fields=['recipient', '-queued_at'], name='email_dispatch_by_recipient'), models.Index(fields=['kind', '-queued_at'], name='email_dispatch_by_kind'), models.Index(fields=['send_status', '-queued_at'], name='email_dispatch_by_send_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['login_code', 'payment_link', 'membership_suspended', 'access_revoked'])), name='email_dispatch_kind_is_known', violation_error_message='That is not an email this platform sends.'), models.CheckConstraint(condition=models.Q(('storefront__in', ['club', 'market'])), name='email_dispatch_storefront_is_known', violation_error_message='That is not a storefront this platform serves.'), models.CheckConstraint(condition=models.Q(models.Q(('send_status', 'sent'), _negated=True), ('sent_at__isnull', False), _connector='OR'), name='email_dispatch_sent_has_a_timestamp', violation_error_message='A sent email has to say when it was sent.'), models.CheckConstraint(condition=models.Q(('delivery_status', 'unknown'), ('delivered_at__isnull', False), _connector='OR'), name='email_dispatch_delivery_has_a_timestamp', violation_error_message='A reported delivery outcome has to say when it was reported.'), models.CheckConstraint(condition=models.Q(models.Q(('read_status', 'read'), _negated=True), ('read_at__isnull', False), _connector='OR'), name='email_dispatch_read_has_a_timestamp', violation_error_message='An opened email has to say when.')],
            },
        ),
    ]
