"""Email sending moved onto a Celery queue. What the schema needed for that.

``body`` is the hand-off: the request composes the message and a worker sends
it, so something has to carry the text between the two processes, and this
column was chosen over a task argument because a task argument sits in Redis in
cleartext and the body holds sign-in codes. It is cleared in the same statement
that settles the row, and the constraint below is what enforces that.

``attempts`` exists because a send is now retried, and ``send_error`` holds only
the most recent failure.

**Safe for the rolling revision the entrypoint describes.** Container Apps
starts the new revision before retiring the old one, so a schema change has to
be readable by the code still serving traffic. Both columns are additive with
defaults, and the constraint is satisfied by every existing row -- they all hold
``body = ''``, because until this migration there was no column to hold anything
else. The old revision writes no ``body``, which is the default, so nothing it
inserts can violate it either.
"""
# Generated by Django 6.1 on 2026-09-02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0002_emaildispatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildispatch',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times a mail server has been asked to take it.'),
        ),
        migrations.AddField(
            model_name='emaildispatch',
            name='body',
            field=models.TextField(blank=True, help_text='The message text, held only until the send settles and then cleared. Empty on every row that has been sent or has failed.'),
        ),
        migrations.AlterField(
            model_name='emaildispatch',
            name='send_status',
            field=models.CharField(choices=[('queued', 'Waiting to be handed over'), ('sent', 'Accepted by the mail server'), ('failed', 'Refused by the mail server')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='emaildispatch',
            name='subject',
            field=models.CharField(help_text='The subject line as sent. Kept for the life of the row.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='emaildispatch',
            constraint=models.CheckConstraint(condition=models.Q(('send_status', 'queued'), ('body', ''), _connector='OR'), name='email_dispatch_body_is_cleared_once_settled', violation_error_message='A sent or failed email must not keep its message text.'),
        ),
    ]
