# Generated by Django 6.1 on 2026-08-27 10:36

import app.core.accounts.models
import app.core.accounts.storage
import app.core.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, help_text='Stored as +27 and nine digits, whatever form it was given in.', max_length=16, validators=[app.core.common.validators.validate_sa_mobile_number])),
                ('mobile_key', models.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_birth_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_number_encrypted', models.TextField(blank=True, editable=False)),
                ('id_number_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('non_authenticating', 'Holds records, never signs in')], db_index=True, default='active', help_text='Whether this identity may sign in. What somebody may *do* is the membership, not this.', max_length=24)),
                ('is_active', models.BooleanField(default=False, editable=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('avatar', models.FileField(blank=True, help_text='Set through the profile endpoint, which crops and re-encodes.', storage=app.core.accounts.storage.avatar_storage, upload_to=app.core.accounts.storage.avatar_upload_to)),
                ('avatar_updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', app.core.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityNumberDisclosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(help_text='Why the number had to be read. Recorded, and never blank.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='identity_disclosures', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_numbers_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'identity number disclosure',
                'verbose_name_plural': 'identity number disclosures',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('is_active', False)), _connector='OR'), name='user_is_active_matches_status', violation_error_message='is_active is derived from status and cannot be set directly.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('mobile_key',), name='user_mobile_key_unique', violation_error_message='Another account already holds that mobile number.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mobile', ''), ('mobile_key__isnull', True)), models.Q(('mobile_key', models.F('mobile')), ('mobile_key__isnull', False)), _connector='OR'), name='user_mobile_key_matches_mobile', violation_error_message='mobile_key is derived from mobile and cannot be set directly.'),
        ),
        migrations.AddIndex(
            model_name='identitynumberdisclosure',
            index=models.Index(fields=['member', '-created_at'], name='idnum_disclosure_member_idx'),
        ),
    ]
