"""The plant, its optional batch, its ownership history, and the serial counter.

One operation here is not generated and is the reason this file is edited by
hand: **the serial counter row is seeded.** `allocate_serials` deliberately
refuses to create it, because a missing counter and a counter at 1 look
identical to code and are completely different to a member -- recreating it
would restart the sequence and reissue serials that are already printed on
certificates of ownership. So the row is written once, here, and its absence
afterwards is an error somebody has to look at rather than something the
application repairs.

Carried forward from the migration set Block 0.5 cleared. `design/migrations.md`
section 3.2 is why it survived that clearing when almost nothing else did.
"""
# Generated by Django 6.1 on 2026-08-27 10:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


#: Must match `models.PLANT_SERIAL_SEQUENCE`. Inlined rather than imported: a
#: migration is a historical record, and a later rename must not change what
#: this one did. `design/migrations.md` section 1.
PLANT_SERIAL_SEQUENCE = 'plant'


def seed_serial_counter(apps, schema_editor):
    """Start the plant sequence at 1. Idempotent, so a re-run is harmless."""
    SerialCounter = apps.get_model('plant', 'SerialCounter')
    SerialCounter.objects.get_or_create(
        name=PLANT_SERIAL_SEQUENCE, defaults={'next_value': 1}
    )


def drop_serial_counter(apps, schema_editor):
    """Reverse. The table goes with the migration, so there is nothing to undo."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
        ('strains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCounter',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'serial counter',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Your own crop or batch number. Unique among your batches.', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('cultivator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_batches', to='producers.producer')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(editable=False, help_text='Allocated by the platform. Appears on the certificate of ownership.', max_length=32)),
                ('cultivator_plant_id', models.CharField(help_text='Your own identifier for this plant, as it is labelled in your greenhouse.', max_length=50)),
                ('grow_price', models.DecimalField(decimal_places=2, help_text='What a member pays to have this plant grown, in Rand.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('leaf_rating', models.DecimalField(decimal_places=1, editable=False, help_text='Swap value: grow price ÷ 1000, to the nearest 0.5. Never shown alongside a Rand value.', max_digits=5)),
                ('minimum_yield_grams', models.DecimalField(decimal_places=2, help_text='The least dry weight, in grams, undertaken for this plant.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('planting_date', models.DateField()),
                ('estimated_bloom_date', models.DateField()),
                ('estimated_harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('preflowering', 'Preflowering'), ('in_bloom', 'In bloom'), ('harvested', 'Harvested'), ('processed', 'Processed'), ('shipped', 'Shipped')], db_index=True, default='preflowering', max_length=16)),
                ('harvested_on', models.DateField(blank=True, editable=False, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Optional crop or batch this plant belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plant.batch')),
                ('listing', models.ForeignKey(help_text='Which of your strain offerings this plant is grown against. Determines the strain, and the finished product types the owner may choose from at harvest.', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='strains.cultivatorstrainlisting')),
                ('owner', models.ForeignKey(blank=True, editable=False, help_text='Blank while the cultivator still holds it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlantOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('purchase', 'Purchased'), ('swap', 'Swapped'), ('allocation', 'Allocated to a sharing member'), ('adjustment', 'Adjusted by staff')], max_length=16)),
                ('current_for_plant', models.UUIDField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_ownerships', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='plant.plant')),
            ],
            options={
                'verbose_name': 'plant ownership',
                'verbose_name_plural': 'plant ownership history',
                'ordering': ('-acquired_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('cultivator', 'reference'), name='one_batch_reference_per_cultivator', violation_error_message='You already have a batch with that reference.'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['listing', 'owner', 'estimated_harvest_date'], name='plant_available_by_date'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['owner', 'status'], name='plant_by_owner'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['batch'], name='plant_by_batch'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('serial',), name='plant_serial_unique', violation_error_message='That platform serial has already been issued.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('listing', 'cultivator_plant_id'), name='one_cultivator_plant_id_per_listing', violation_error_message='You have already used that plant ID for this strain.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['preflowering', 'in_bloom', 'harvested', 'processed', 'shipped'])), name='plant_status_is_known', violation_error_message='That is not a plant status this platform recognises.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('grow_price__gt', 0)), name='plant_grow_price_is_positive', violation_error_message='A grow price must be more than zero.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_yield_grams__gt', 0)), name='plant_minimum_yield_is_positive', violation_error_message='A minimum yield must be more than zero.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('leaf_rating__gte', 0)), name='plant_leaf_rating_is_not_negative', violation_error_message='A leaf rating cannot be negative.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('harvested_on__isnull', False), ('status__in', ['harvested', 'processed', 'shipped'])), models.Q(models.Q(('status__in', ['harvested', 'processed', 'shipped']), _negated=True), ('harvested_on__isnull', True)), _connector='OR'), name='harvested_plant_has_a_harvest_date', violation_error_message='A harvested plant needs an actual harvest date, and an unharvested one cannot have had one.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_harvest_date__gte', models.F('planting_date'))), name='plant_harvest_follows_planting', violation_error_message='A plant cannot be harvested before it was planted.'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_bloom_date__gte', models.F('planting_date'))), name='plant_bloom_follows_planting', violation_error_message='A plant cannot flower before it was planted.'),
        ),
        migrations.AddIndex(
            model_name='plantownership',
            index=models.Index(fields=['plant', '-acquired_at'], name='tenure_by_plant'),
        ),
        migrations.AddIndex(
            model_name='plantownership',
            index=models.Index(fields=['owner', '-acquired_at'], name='tenure_by_owner'),
        ),
        migrations.AddConstraint(
            model_name='plantownership',
            constraint=models.UniqueConstraint(fields=('current_for_plant',), name='one_open_tenure_per_plant', violation_error_message='That plant already has an open ownership record.'),
        ),
        migrations.AddConstraint(
            model_name='plantownership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_for_plant', models.F('plant')), ('current_for_plant__isnull', False), ('released_at__isnull', True)), models.Q(('current_for_plant__isnull', True), ('released_at__isnull', False)), _connector='OR'), name='current_for_plant_matches_released_at', violation_error_message='current_for_plant is derived from released_at and cannot be set directly.'),
        ),
        migrations.AddConstraint(
            model_name='plantownership',
            constraint=models.CheckConstraint(condition=models.Q(('released_at__isnull', True), ('released_at__gte', models.F('acquired_at')), _connector='OR'), name='tenure_ends_after_it_starts', violation_error_message='A tenure cannot end before it began.'),
        ),
        # Last, so the table it writes to certainly exists. See the module
        # docstring on why this is a migration rather than a get_or_create in
        # the allocator.
        migrations.RunPython(seed_serial_counter, drop_serial_counter),
    ]
