# Generated by Django 6.1 on 2026-08-27 10:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('pending_payment', 'Pending payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('lapsed', 'Lapsed'), ('sharing', 'Sharing member (no sign-in)')], db_index=True, default='pending', max_length=16)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('nickname_key', models.CharField(blank=True, editable=False, max_length=60, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, help_text='The producer whose stock this placeholder holds.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharing_placeholders', to='producers.producer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'club membership',
                'ordering': ('-joined_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'pending_payment', 'active', 'suspended', 'lapsed', 'sharing'])), name='club_membership_status_is_known', violation_error_message='That is not a membership status this platform recognises.'), models.UniqueConstraint(fields=('nickname_key',), name='club_membership_nickname_key_unique', violation_error_message='That nickname is already taken.'), models.CheckConstraint(condition=models.Q(models.Q(('nickname', ''), ('nickname_key__isnull', True)), models.Q(('nickname_key', django.db.models.functions.text.Lower('nickname')), ('nickname_key__isnull', False)), _connector='OR'), name='club_membership_nickname_key_matches_nickname', violation_error_message='nickname_key is derived from nickname and cannot be set directly.'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'sharing'), _negated=True), ('registered_by__isnull', False), _connector='OR'), name='club_membership_sharing_member_has_a_cultivator', violation_error_message='A sharing member holds a cultivator’s stock, so it needs the cultivator it was created under.')],
            },
        ),
    ]
