# Generated by Django 6.1 on 2026-09-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='first_touch',
            field=models.ForeignKey(blank=True, help_text='The campaign that first brought this visitor here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attribution.campaigntouch'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='last_touch',
            field=models.ForeignKey(blank=True, help_text='The campaign on the visit they converted on. The same row as the first touch where that was one and the same visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attribution.campaigntouch'),
        ),
    ]
