# Generated by Django 6.1 on 2026-08-26 06:23

import app.cultivators.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_description', models.TextField(blank=True, help_text='Your description of your farm, shown to members. Compliance-governed copy: no claim about what cannabis does.')),
                ('image', models.ImageField(blank=True, help_text='One photograph, shown beside your name.', upload_to=app.cultivators.models.profile_image_upload_to)),
                ('is_published', models.BooleanField(default=False, help_text='Members see this profile only once it is published.')),
                ('cultivator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cultivator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cultivator profile',
                'ordering': ('cultivator__nickname',),
            },
        ),
    ]
