"""Documents, revisions, agreements — and the three the club asks about.

The seed at the end is not generated. It registers the three documents the
sign-up form already asks about, **by identity only**: no revisions, because the
files on the CDN predate this app and nothing here knows their digests, and a
seeded revision would carry a blank `sha256` -- an unverifiable row in the one
table whose entire job is to be verifiable.

So sign-up fails closed until each document has a revision published through the
admin or `manage.py publish_document`. That is a deliberate one-time step, and
it is what gets a real digest recorded for every file a member is ever shown.

Carried forward from the migration set Block 0.5 cleared, with the columns C26
added. `design/migrations.md` section 3.1.
"""
# Generated by Django 6.1 on 2026-08-27 10:36

import app.core.documents.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


#: The club's three, seeded against the club storefront. Written out rather than
#: imported: a migration is a historical record and must keep saying what it
#: once said. `design/migrations.md` section 1.
#:
#: `audience=customer` and `agreement=at_registration`: read by anybody, because
#: sign-up shows them before an account exists, and ticked when joining.
#:
#: The market's own terms, privacy notice and data policy are **not** here. They
#: are new rows at `audience=public`, `agreement=none`, and there is no content
#: for them yet.
CLUB_DOCUMENTS = [
    ('club-rules', 'Club Rules', 0),
    ('annexures', 'Annexures', 1),
    ('constitution', 'Constitution', 2),
]


def seed(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for slug, title, position in CLUB_DOCUMENTS:
        Document.objects.update_or_create(
            storefront='club',
            slug=slug,
            defaults={
                'title': title,
                'position': position,
                'audience': 'customer',
                'agreement': 'at_registration',
            },
        )


def unseed(apps, schema_editor):
    """Remove the three rows, but never one that has a revision.

    A document with revisions has agreements pointing through it, and the
    foreign keys are PROTECT for that reason. Reversing this on a database that
    has been used is not something to force through.
    """
    Document = apps.get_model('documents', 'Document')
    Document.objects.filter(
        storefront='club',
        slug__in=[slug for slug, *_ in CLUB_DOCUMENTS],
        versions__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storefront', models.CharField(choices=[('club', 'Cultivators Collective'), ('market', 'Produce market')], db_index=True, help_text='Which storefront this document belongs to. Never both.', max_length=16)),
                ('audience', models.CharField(choices=[('public', 'Anyone'), ('customer', 'Members and customers'), ('producer', 'Producers')], db_index=True, default='customer', max_length=16)),
                ('agreement', models.CharField(choices=[('none', 'No agreement needed'), ('at_registration', 'Agreed when joining'), ('at_onboarding', 'Agreed when a producer is onboarded')], db_index=True, default='at_registration', max_length=20)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Set to retire a document without deleting it or the agreements already given to it. The only safe way to withdraw one.', null=True)),
                ('slug', models.SlugField(help_text='Stable identifier used by the sign-up form, e.g. "constitution". Never change this on a document people have already agreed to.', max_length=60)),
                ('title', models.CharField(help_text='What a member sees, e.g. "Constitution".', max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Low numbers first on the sign-up form.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document',
                'ordering': ('position', 'slug'),
                'constraints': [models.UniqueConstraint(fields=('storefront', 'slug'), name='document_slug_unique_per_storefront', violation_error_message='That storefront already has a document with this slug.'), models.CheckConstraint(condition=models.Q(('storefront__in', ['club', 'market'])), name='document_storefront_is_known'), models.CheckConstraint(condition=models.Q(('audience__in', ['public', 'customer', 'producer'])), name='document_audience_is_known'), models.CheckConstraint(condition=models.Q(('agreement__in', ['none', 'at_registration', 'at_onboarding'])), name='document_agreement_is_known'), models.CheckConstraint(condition=models.Q(models.Q(('audience', 'public'), _negated=True), ('agreement', 'none'), _connector='OR'), name='document_public_needs_no_agreement', violation_error_message='A public document is read, not agreed to. Give it an audience of members or producers if agreement is needed.')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='This revision\'s version, e.g. "2" or "2026-08". Unique per document.', max_length=32, validators=[django.core.validators.RegexValidator(message='A version label must start with a letter or digit and may contain only letters, digits, dots, dashes and underscores.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('file', models.FileField(help_text='The PDF as members will read it. Uploaded straight to the CDN.', max_length=255, storage=app.core.documents.storage.document_storage, upload_to=app.core.documents.storage.document_upload_to)),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0, editable=False)),
                ('consent_text', models.TextField(help_text='The exact sentence a member ticks, e.g. "I have read and agree to the Constitution". Recorded against every agreement.')),
                ('consent_text_sha256', models.CharField(editable=False, max_length=64)),
                ('change_note', models.TextField(blank=True, help_text='Staff-facing: what changed in this revision, and who decided it.')),
                ('requires_reacceptance', models.BooleanField(default=False, help_text='Tick when the change is material. Members who agreed to an earlier revision will be asked again; leave unticked for a typo fix.')),
                ('effective_from', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document version',
                'ordering': ('document__position', '-effective_from', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('file_sha256', models.CharField(editable=False, max_length=64)),
                ('consent_text_sha256', models.CharField(editable=False, max_length=64)),
                ('source', models.CharField(choices=[('signup', 'Sign-up'), ('reacceptance', 'Re-acceptance'), ('admin', 'Recorded by staff')], default='signup', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_consents', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'document agreement',
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.CreateModel(
            name='ProducerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('file_sha256', models.CharField(editable=False, max_length=64)),
                ('consent_text_sha256', models.CharField(editable=False, max_length=64)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='producers.producer')),
                ('signed_by', models.ForeignKey(blank=True, help_text='Who ticked, on the organisation’s behalf. Blank once erased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_agreements_signed', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_agreements', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'producer agreement',
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'label'), name='document_version_label_unique_per_document', violation_error_message='That version label is already used for this document.'),
        ),
        migrations.AddIndex(
            model_name='documentconsent',
            index=models.Index(fields=['user', 'version'], name='documents_d_user_id_b7272a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentconsent',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='document_consent_once_per_version', violation_error_message='This member has already agreed to that revision.'),
        ),
        migrations.AddIndex(
            model_name='produceragreement',
            index=models.Index(fields=['producer', 'version'], name='documents_p_produce_1de0d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='produceragreement',
            constraint=models.UniqueConstraint(fields=('producer', 'version'), name='producer_agreement_once_per_version', violation_error_message='This producer has already agreed to that revision.'),
        ),
        # Last, so every table it touches certainly exists.
        migrations.RunPython(seed, unseed),
    ]
