"""
Django settings for f2c project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Safe to import here: it reads an environment mapping and touches no model and
# no setting, so it does not need the app registry that this file is loaded to
# build. See its module docstring for why the reader lives there and not here.
from app.core.accounts.storage import avatars_storage_config
from app.core.documents.storage import documents_storage_config
from app.core.payments.gateway import payfast_config

from .cache import cache_config
from .database import database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env into the process environment for local development. In deployed
# environments set real environment variables and ship no .env file.
try:
    from dotenv import load_dotenv
except ImportError:
    pass
else:
    load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Read a boolean from the environment. Accepts 1/true/yes/on."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    """Read a comma-separated list from the environment.

    A variable that is present but empty falls back to the default. Without
    that, the blank placeholders in .env.example would silently override every
    default here.
    """
    raw = os.environ.get(name) or ''
    if not raw.strip():
        raw = default
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set. Copy .env.example to .env and fill it in, '
        'or export the variable in your environment.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default='127.0.0.1,localhost' if DEBUG else '',
)

# Needed once the site is served over HTTPS behind a proxy or on a real domain.
# The Next.js origin must appear here, otherwise its POSTs fail CSRF checks.
CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000' if DEBUG else '',
)


# Cross-origin requests from the Next.js frontend
# https://github.com/adamchainz/django-cors-headers

# Next.js runs on its own origin, so the browser treats every API call as
# cross-origin. Only the origins listed here may read responses.
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000' if DEBUG else '',
)

# Required for session-cookie auth: without it the browser sends no cookies.
CORS_ALLOW_CREDENTIALS = True

# The frontend reads this token from JavaScript and echoes it in X-CSRFToken,
# so it cannot be HttpOnly. The session cookie stays HttpOnly.
CSRF_COOKIE_HTTPONLY = False

# 'Lax' is enough because each frontend calls an API host inside its own
# registrable domain -- the store at f2c.co.za calls backend.f2c.co.za, the club
# at f2c-cannabis.co.za calls backend.f2c-cannabis.co.za. That pairing is the
# whole reason there are two API hostnames: cross the domains and the cookie
# needs 'None', which Safari's ITP and Chrome's third-party cookie posture drop
# anyway. See design/conflict.md C30 and design/verticals.md section 8.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# SESSION_COOKIE_DOMAIN is deliberately unset. One deployment answering on two
# registrable domains cannot name a single cookie domain, and host-only cookies
# per API host are what the pairing above needs.

# Cookies must never travel in cleartext outside local development.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# HTTPS, and what Django is allowed to believe about it

# **One variable for one deployment fact.** Every container deployment has
# something terminating TLS in front of Django -- Container Apps ingress, a load
# balancer, a CDN -- and three separate things need to know: Django, so it does
# not redirect a request that already arrived over HTTPS into a loop; the
# Payfast notification endpoint, so it reads the caller's address rather than
# the proxy's; and HSTS, which is meaningless on a connection Django thinks is
# plain. `payfast_config` reads this same variable, which is why there is one
# and not two: two switches for one fact fail by having one of them set.
BEHIND_PROXY = env_bool('DJANGO_BEHIND_PROXY')

# Only consulted when BEHIND_PROXY says the edge is trustworthy. The header is
# client-supplied like any other, so believing it in front of nothing lets a
# caller declare their own plain-HTTP request secure -- and Django would then
# set a Secure cookie on it and skip the redirect.
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https') if BEHIND_PROXY else None
)

# Off in development, and off when nothing in front of Django is known to speak
# HTTPS -- switching it on without SECURE_PROXY_SSL_HEADER is the redirect loop
# this pairing exists to avoid.
SECURE_SSL_REDIRECT = env_bool(
    'DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG and BEHIND_PROXY
)

# A year, and only outside development. Deliberately not `preload`: the preload
# list is close to irreversible and covers every subdomain of a registrable
# domain, which here would include hosts this project does not serve.
SECURE_HSTS_SECONDS = 0 if DEBUG else int(
    os.environ.get('DJANGO_SECURE_HSTS_SECONDS') or 31_536_000
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG
)

# `security.W021` asks why SECURE_HSTS_PRELOAD is not set, and the answer is
# that it is not wanted. Submitting to the browser preload list is close to
# irreversible -- removal takes months and reaches users only as they update --
# and it applies to the whole registrable domain including subdomains this
# project does not serve and may not always control. HSTS itself is on above,
# which is the part that protects members.
#
# Silenced rather than left to be re-read every deploy, because the container
# entrypoint runs `check --deploy --fail-level WARNING`: an accepted warning
# left in place would mean the gate could never pass, and a gate that cannot
# pass gets removed. The list is for decisions, never for things not yet fixed.
SILENCED_SYSTEM_CHECKS = ['security.W021']


# Storefronts
# https://design/verticals.md section 8

def _storefront_hosts(raw):
    """``host=storefront,host=storefront`` into a mapping. Blank is no mapping.

    A mapping rather than a table: the hosts a deployment answers on are already
    environment configuration -- ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS above --
    and adding a QA domain should not need a migration. See
    ``app.core.storefronts.resolution``.
    """
    pairs = {}
    for entry in (raw or '').split(','):
        entry = entry.strip()
        if not entry or '=' not in entry:
            continue
        host, _, storefront = entry.partition('=')
        host = host.strip().lower()
        storefront = storefront.strip().lower()
        if host and storefront:
            pairs[host] = storefront
    return pairs


# These are the hosts *Django* answers on, not the ones the browser shows. The
# frontend's name never reaches here; `request.get_host()` is the API host. So the
# production mapping is:
#
#   DJANGO_STOREFRONT_HOSTS=backend.f2c.co.za=market,backend.f2c-cannabis.co.za=club
STOREFRONT_HOSTS = _storefront_hosts(os.environ.get('DJANGO_STOREFRONT_HOSTS'))

# Where an unmapped host lands. The club, because it is the only storefront that
# exists today and because serving its *public* documents to an unrecognised
# host discloses nothing that is not already public.
DEFAULT_STOREFRONT = os.environ.get('DJANGO_DEFAULT_STOREFRONT', 'club')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'corsheaders',

    # Local, grouped the way `design/verticals.md` section 7 sets out. Each app
    # owns its own models, admin, schemas and router, and the routers are
    # mounted in one place -- see ROOT_URLCONF's api module.
    #
    # `core` is the platform spine and knows nothing about what is sold.
    # `commerce` is what both storefronts sell through. `club` is the cannabis
    # vertical. `market` is the produce vertical and has no apps yet.
    #
    # Every app sets `label` explicitly, so the table names stay flat and the
    # move under these packages did not rename a single table.
    'app.core.common',
    'app.core.accounts',
    'app.core.authn',
    'app.core.storefronts',
    'app.core.documents',
    'app.core.payments',

    'app.commerce.producers',

    'app.club.membership',
    'app.club.strains',
    'app.club.finished_product',
    'app.club.plant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware so preflight responses are not redirected.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f2c.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Used by 'manage.py runserver', which is WSGI-only in Django 6.1.
WSGI_APPLICATION = 'f2c.wsgi.application'

# ASGI entrypoint, served by Uvicorn: f2c.asgi:application


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite on a developer's machine, MySQL 8.4 in QA and production. Read once at
# startup by a pure function of the environment, the same shape as the storage
# and Payfast readers -- `database.py` has the reasoning, including why
# `sql_mode` is named in full and why the test database is given an explicit
# collation.
#
# `common/checks.py` is what refuses a MySQL too old to enforce a check
# constraint, and it runs on `migrate`. Nothing here validates the version,
# because a settings module that opened a connection would make every management
# command depend on the database being up.
DATABASES = {'default': database_config(os.environ, BASE_DIR)}


# Authentication: the user model
# https://docs.djangoproject.com/en/6.1/topics/auth/customizing/#substituting-a-custom-user-model

# Members and staff are the same model, told apart by is_staff. Changing this
# after the project has real data is close to impossible, which is why it is
# set from the first migration rather than deferred.
AUTH_USER_MODEL = 'accounts.User'

# Two backends, one of which authenticates nobody.
#
# ModelBackend is the only one that can open a session, and every session is
# attributed to it -- the passkey and emailed-code paths in `authn/api.py` name
# it explicitly for that reason. RoleBackend answers `has_perm` for the
# `platform.*` action catalogue in `accounts/roles.py` and returns None from
# `authenticate`, so ordering it second is what keeps the two concerns apart:
# credentials above, authority below.
#
# The point of resolving platform actions through a backend rather than a
# bespoke helper is that one call -- `user.has_perm(...)` -- covers both kinds
# of permission, so a view never has to know which kind it named.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'app.core.accounts.backends.RoleBackend',
]


# Field-level encryption
# See common/crypto.py for what each of these protects and why they are separate
# from DJANGO_SECRET_KEY.

# 32 bytes, base64. Encrypts identity-document numbers at rest. Losing it makes
# every stored ID number unrecoverable; leaking it exposes all of them.
FIELD_ENCRYPTION_KEY = os.environ.get('DJANGO_FIELD_ENCRYPTION_KEY', '')

# 32 bytes, base64. Keys the searchable digests of ID numbers and email
# addresses. Changing it invalidates every stored digest, so uniqueness checks
# and "have we seen this address" lookups would need a rebuild.
BLIND_INDEX_PEPPER = os.environ.get('DJANGO_BLIND_INDEX_PEPPER', '')

if not FIELD_ENCRYPTION_KEY or not BLIND_INDEX_PEPPER:
    raise ImproperlyConfigured(
        'DJANGO_FIELD_ENCRYPTION_KEY and DJANGO_BLIND_INDEX_PEPPER must both be '
        'set. Generate each with:\n'
        '    python -c "import base64, secrets; '
        'print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())"'
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Django serves no pages of its own -- everything here is the admin's brand skin
# (see static/cc_admin/ and templates/admin/base_site.html). The cc_admin/ prefix
# keeps it clear of django.contrib.admin's own static/admin/ tree, so nothing here
# can shadow an upstream admin asset.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Only used by collectstatic. Without it the admin's stylesheets and the brand skin
# both 404 once DEBUG is off, because runserver's static handler is gone and nothing
# has written the files anywhere a web server can find them.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Club documents: where the files are stored and how they are addressed
#
# Azure Blob Storage, fronted by the CDN. Every variable behind this is read and
# validated by documents.storage.documents_storage_config, which is a pure
# function of an environment mapping -- so the refusals that matter (a CDN base
# that is not https, or whose path disagrees with the container name) are tested
# without an Azure account, and are named in one place rather than described here
# as well. See documents/models.py for what is recorded about each revision.
#
# Note that with a container configured, django-storages must be installed for
# Django to start: FileField resolves a callable storage at import. That is the
# intended failure -- immediate and named, rather than an upload that works on a
# developer's disk and dies in the admin.

# Defining STORAGES replaces Django's defaults wholesale, so 'default' and
# 'staticfiles' are restated here rather than inherited.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
    },
    # Deliberately not 'default': whatever else this project ever stores must not
    # land in the container the CDN serves to the public. Azure Blob Storage when
    # DJANGO_DOCUMENT_STORAGE_CONTAINER is set, local disk otherwise.
    'documents': documents_storage_config(os.environ, debug=DEBUG),
    # Member avatars, and the reason there is a third alias rather than a second
    # use of 'documents'. A club document is published to everybody; an avatar is
    # a photograph of somebody's face. This container is private, has no CDN in
    # front of it and no URL at all -- GET /api/accounts/me/avatar checks the
    # session and streams the bytes. accounts/storage.py refuses a configuration
    # that names the documents container here, because that mistake would publish
    # every member's photograph. Azure Blob Storage when
    # DJANGO_AVATAR_STORAGE_CONTAINER is set, local disk otherwise.
    'avatars': avatars_storage_config(os.environ),
}

# Only reached by the filesystem fallbacks above. Served by runserver under
# DEBUG (see the project URLconf); a deployment with no container configured
# needs a real web server on this path.
#
# Avatars land here too when no avatar container is configured, and under DEBUG
# that means runserver's static handler will serve one to anybody who guesses
# the path. Acceptable in local development and nowhere else: a deployment
# either configures a private container or puts a web server on this path that
# does not serve the avatars prefix. Recorded here rather than left to be
# discovered.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# **Two SMTP servers, and the split is by storefront rather than by message.**
# The club and the produce market are separate businesses on separate registrable
# domains, and each has its own mailbox provider. Club mail leaves the club's
# server (`EMAIL_CC_*`), market mail leaves the store's (`EMAIL_F2C_*`), and that
# includes the sign-in code -- a store customer must not receive a club-branded
# email from a club domain, and the club's provider would refuse to send it as
# the store anyway.
#
# The aliases are the storefront codes themselves, so routing is
# `.send(using=storefront)` with nothing to look up. That is the same shape as
# `WEBAUTHN_RP_IDS` above and for the same reason -- see
# `app.core.storefronts.mail`, which is the one place a caller asks.
#
# The literals are spelled out rather than imported from `Storefront`: this file
# is loaded to *build* the app registry, so it cannot import a models module.
# `storefronts.checks` asserts the two agree, which is what keeps the duplication
# honest.

# The address OTP emails are sent from when a storefront names none of its own.
# Django's default is 'webmaster@localhost'.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@f2c.co.za'
)


def _mailer(prefix, storefront):
    """One SMTP mailer from the ``EMAIL_<prefix>_*`` variables.

    **A blank host is fatal outside local development.** It would otherwise fall
    back to some other storefront's server, and that failure is quiet in the
    worst way: the mail sends, so nothing looks wrong, and the store's members
    receive a club-signed email from a provider that has no business holding
    their address. The same call `payfast_config` makes about a sandbox merchant.

    Locally a blank host means the console backend, so the whole flow -- sign-in
    codes included -- works with no mail server at all.
    """
    host = (os.environ.get(f'EMAIL_{prefix}_HOST') or '').strip()
    if not host:
        if not DEBUG:
            raise ImproperlyConfigured(
                f'EMAIL_{prefix}_HOST is not set. It is the SMTP server the '
                f'{storefront} storefront sends from, and there is deliberately '
                "no fallback: sending one storefront's mail through another's "
                'server succeeds silently and is wrong.'
            )
        return {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}

    # TLS unless SSL is asked for, and defaulted *on*: a password crossing the
    # network in cleartext is not something to arrive at by leaving a variable
    # blank. Implicit SSL on 465 is common with South African providers, which
    # is why both spellings exist.
    use_ssl = env_bool(f'EMAIL_{prefix}_USE_SSL', default=False)
    use_tls = env_bool(f'EMAIL_{prefix}_USE_TLS', default=not use_ssl)
    if use_tls and use_ssl:
        raise ImproperlyConfigured(
            f'EMAIL_{prefix}_USE_TLS and EMAIL_{prefix}_USE_SSL are mutually '
            f'exclusive. STARTTLS on 587 is EMAIL_{prefix}_USE_TLS; implicit '
            f'TLS on 465 is EMAIL_{prefix}_USE_SSL.'
        )

    raw_port = (os.environ.get(f'EMAIL_{prefix}_PORT') or '').strip()
    try:
        port = int(raw_port) if raw_port else (465 if use_ssl else 587)
    except ValueError:
        raise ImproperlyConfigured(
            f'EMAIL_{prefix}_PORT must be a whole number, not {raw_port!r}.'
        ) from None

    return {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': host,
            'port': port,
            'username': (os.environ.get(f'EMAIL_{prefix}_USER') or '').strip(),
            'password': os.environ.get(f'EMAIL_{prefix}_PASSWORD') or '',
            'use_tls': use_tls,
            'use_ssl': use_ssl,
            # Bounded, because this send happens in a worker thread the sign-in
            # request is waiting on. An unreachable mail server must fail rather
            # than hold the thread until the client gives up.
            'timeout': 10,
        },
    }


def _from_email(prefix, storefront):
    """The address one storefront's mail is sent as.

    Not a `MAILERS` key -- Django has none -- so it is read here and applied by
    `storefronts.mail`. Required outside local development for the same reason
    the host is: most providers reject a `From` they do not own, and the two
    storefronts are on different domains, so one shared sender address cannot be
    right for both.
    """
    value = (os.environ.get(f'EMAIL_{prefix}_FROM') or '').strip()
    if value:
        return value
    if not DEBUG:
        raise ImproperlyConfigured(
            f'EMAIL_{prefix}_FROM is not set. It is the address the '
            f'{storefront} storefront sends as, e.g. no-reply@example.co.za, '
            'and it normally has to be one the provider above is authorised to '
            'send for.'
        )
    return DEFAULT_FROM_EMAIL


# The test suite must not reach a mail server. Django only stubs
# `EMAIL_BACKEND`, which nothing here sends through -- see `f2c.test_runner`.
TEST_RUNNER = 'f2c.test_runner.MailSafeRunner'

MAILERS = {
    'club': _mailer('CC', 'club'),
    'market': _mailer('F2C', 'market'),
}

# Django requires a `default`, and it is what anything sending without a
# storefront gets -- `mail_admins`, `sendtestemail`, the admin error handler.
# Pointed at the default storefront rather than hardcoded, so a deployment that
# flips DJANGO_DEFAULT_STOREFRONT does not leave its unrouted mail behind.
MAILERS['default'] = MAILERS.get(DEFAULT_STOREFRONT) or MAILERS['club']

#: ``{storefront: from address}``. Read through `storefronts.mail.from_email_for`.
STOREFRONT_FROM_EMAIL = {
    'club': _from_email('CC', 'club'),
    'market': _from_email('F2C', 'market'),
}

#: How long a send is kept in `storefronts.EmailDispatch`, in days.
#:
#: The log answers "was this member told?", and that question has a shelf life:
#: a sign-in code nobody can remember requesting is a support call this week, not
#: next year. Twelve months is the default because the longest-lived question is
#: a membership dispute over a suspension notice, which is annual.
#:
#: Nothing enforces this on its own -- POPIA's retention principle is a
#: schedule, and the schedule is `manage.py purge_email_dispatches` on a timer.
#: Zero disables the purge, for a deployment that would rather keep everything
#: and say so.
EMAIL_DISPATCH_RETENTION_DAYS = int(
    (os.environ.get('EMAIL_DISPATCH_RETENTION_DAYS') or '365').strip() or 365
)


# Cache
# https://docs.djangoproject.com/en/6.1/topics/cache/

# Rate limiting for the auth endpoints is enforced through the cache, so it has
# to be a backend every process and every replica can see. `LocMemCache` was
# not: it gave each Uvicorn worker its own counters, which multiplied every
# published limit by the worker count -- including the one bounding outbound
# email, whose whole job is to stop `otp/start` being used as a mailbomb relay.
#
# Redis in every environment; Azure Managed Redis in QA and production, the
# container in `compose.yaml` locally. `f2c/cache.py` carries the reasoning,
# including why the database cache cannot serve this and was reverted.
CACHES = {'default': cache_config(os.environ)}


# Authentication: passkeys (WebAuthn)

# The Relying Party ID is a registrable domain, never a URL and never an IP
# address. It must be the frontend's hostname or a parent of it, because the
# credential is bound to the origin the JavaScript runs on -- not to Django's.
# Locally that means signing in at http://localhost:3000, not 127.0.0.1.
WEBAUTHN_RP_ID = os.environ.get('DJANGO_WEBAUTHN_RP_ID') or (
    'localhost' if DEBUG else ''
)

WEBAUTHN_RP_NAME = os.environ.get('DJANGO_WEBAUTHN_RP_NAME', 'Cultivators Collective')

# **A passkey does not cross a registrable domain.** The club and the produce
# market are on separate ones, so a credential enrolled on the club's domain
# cannot be presented on the market's, and the RP ID has to follow the
# storefront rather than the deployment. `design/verticals.md` section 8.
#
# Same shape as DJANGO_STOREFRONT_HOSTS: `storefront=domain` pairs.
#
#   DJANGO_WEBAUTHN_RP_IDS=club=f2c-cannabis.co.za,market=f2c.co.za
#
# The domains here are the FRONTENDS', not the API hosts above -- a credential is
# bound to the origin the JavaScript runs on.
#
# Anything not listed falls back to WEBAUTHN_RP_ID above, which is what keeps a
# single-storefront deployment configured exactly as it was.
WEBAUTHN_RP_IDS = _storefront_hosts(os.environ.get('DJANGO_WEBAUTHN_RP_IDS'))

# Full origins (scheme, host, port) that may present credentials for the RP ID
# above. Normally identical to DJANGO_CORS_ALLOWED_ORIGINS.
WEBAUTHN_ORIGINS = env_list(
    'DJANGO_WEBAUTHN_ORIGINS',
    default='http://localhost:3000' if DEBUG else '',
)

# How long a generated challenge stays valid, in seconds. Kept short: it is
# held in the session between the two halves of a ceremony.
WEBAUTHN_CHALLENGE_TTL_SECONDS = 300


# Authentication: email one-time passcodes

OTP_CODE_LENGTH = 6

# Five minutes is long enough for an email to arrive and short enough that a
# leaked code is worthless by the time it is found.
OTP_TTL_SECONDS = 300

# Verification attempts against a single code before it is burned. Without this
# a six-digit code is brute-forceable.
OTP_MAX_ATTEMPTS = 5


# Throttling
# https://django-ninja.dev/guides/throttling/

# Scopes referenced by the throttle classes in authn/throttles.py. Rates are
# per client IP; the OTP send rate is the one that stops the API being used to
# mailbomb a member.
NINJA_DEFAULT_THROTTLE_RATES = {
    'auth_start': '20/m',
    'otp_start': '5/m',
    'otp_verify': '10/m',
    'passkey_verify': '20/m',
    # Tighter than the rest on purpose: a person joins a club once, and
    # nothing legitimate registers twice in a minute. See
    # membership/throttles.py -- this is the control that stands in for the
    # CSRF check an unauthenticated, server-to-server endpoint cannot have.
    'register': '5/m',
    # Creating a store account. The same shape and the same job as `register`
    # above, and a scope of its own so the two can be tuned apart: one
    # storefront is a club somebody joins once and the other is a shop. Held at
    # the same rate because a registration also emails a sign-in code, so the
    # limit bounds mail to a typed address as well as rows in the table. See
    # accounts/throttles.py.
    'customer_register': '5/m',
    # The nickname check the sign-up form makes when the field loses focus.
    # Looser than `register`: a member tries a few names in one sitting, and
    # each one is a request. See membership/throttles.py.
    'nickname_availability': '30/m',
    # Reading a checkout. Generous, because it is read again every time a
    # member returns to an abandoned Payfast page, and the control that
    # actually bounds token guessing is the 32 bytes of entropy in the
    # token. See payments/throttles.py -- and note that the Payfast
    # notification endpoint is deliberately not listed here at all.
    'checkout': '30/m',
    # Uploading an avatar. Keyed on the account rather than the IP, which is
    # what the rest of this list cannot do -- these endpoints need a session.
    # Tight because each request decodes and re-encodes an image up to 8MB,
    # which is the most expensive thing a member can ask this API to do, and
    # nothing legitimate replaces a photograph ten times a minute. See
    # accounts/throttles.py.
    'avatar_upload': '10/m',
    # Writing the three editable profile fields. Cheap, but a member editing
    # their own record has no reason to save it thirty times a minute either.
    'profile_write': '20/m',
}


# Payments: Payfast

# Read once at startup by a pure function of the environment, the same shape as
# STORAGES['documents'] above -- so every refusal it can raise is testable
# without a merchant account. With DEBUG on and nothing configured it returns
# Payfast's published sandbox merchant, so a fresh clone works; with DEBUG off
# every variable is required and startup fails without them, because a payment
# integration that silently falls back to a sandbox is one that takes a
# member's money into an account nobody is watching.
#
# One thing configuration cannot fix locally: Payfast delivers notifications
# server-to-server and cannot reach a localhost notify_url, so the step that
# activates a membership never fires on a developer's machine. The
# `payfast_notify` management command stands in for it.
PAYFAST = payfast_config(os.environ, debug=DEBUG)
