# Generated by Django 6.1 on 2026-08-26 06:23

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable machine key, e.g. 'pre-roll'. Referenced in code and in the cultivator upload template, so it is not renamed.", max_length=32)),
                ('name', models.CharField(help_text='What a member sees, e.g. Pre-rolls.', max_length=60)),
                ('description', models.TextField(blank=True, help_text='Shown to a member choosing a type at harvest. Plain description of the form only -- no claim about what it does.')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing cost to the member, in Rand. Zero means the choice is free, which is the case for pre-rolls and loose.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_available', models.BooleanField(default=True, help_text='Clear this to stop offering the type. Never delete a type that has been chosen -- the harvest records point at it.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower sorts first. Ties fall back to name.')),
            ],
            options={
                'verbose_name': 'finished product type',
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('code',), name='finished_product_type_code_unique', violation_error_message='Another product type already uses that code.'), models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='finished_product_type_price_not_negative', violation_error_message='A product type cannot have a negative price.')],
            },
        ),
    ]
