# Generated by Django 6.1 on 2026-09-02 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('payments.lapse_memberships', 'Lapse memberships that have stopped paying'), ('storefronts.purge_email_dispatches', 'Purge send records past their retention window'), ('attribution.purge_campaign_touches', 'Purge campaign touches past their retention window')], db_index=True, help_text='The scheduled job that ran.', max_length=64)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='running', help_text='How the run ended. “Running” on an old row is a run that died without finishing.', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Empty while the run is in progress, and for a run that died.', null=True)),
                ('affected', models.PositiveIntegerField(default=0, help_text='How many rows the run changed or deleted.')),
                ('detail', models.TextField(blank=True, help_text='The failure, in one line. The full traceback is in the worker’s log. Blank for a run that succeeded.')),
            ],
            options={
                'verbose_name': 'scheduled run',
                'verbose_name_plural': 'scheduled runs',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['task', '-started_at'], name='scheduled_run_by_task')],
            },
        ),
    ]
