# Generated by Django 6.1 on 2026-08-27 10:36

import app.core.payments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Awaiting first payment'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('lapsed', 'Lapsed (unpaid)')], db_index=True, default='pending', max_length=16)),
                ('live_for_user', models.UUIDField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.PositiveSmallIntegerField(choices=[(3, 'Monthly'), (4, 'Quarterly'), (5, 'Biannual'), (6, 'Annual')], help_text='How often Payfast bills this subscription.')),
                ('cycles', models.PositiveSmallIntegerField(default=0, help_text='Billing cycles to take, or 0 for until cancelled.')),
                ('checkout_token', models.CharField(default=app.core.payments.models.new_checkout_token, editable=False, max_length=64, unique=True)),
                ('checkout_expires_at', models.DateTimeField()),
                ('gateway_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lapsed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_payment_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('covers_until', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.subscription')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('live_for_user',), name='one_live_subscription_per_member', violation_error_message='That member already holds a live subscription.'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('live_for_user', models.F('user')), ('live_for_user__isnull', False), ('status__in', ['pending', 'active'])), models.Q(models.Q(('status__in', ['pending', 'active']), _negated=True), ('live_for_user__isnull', True)), _connector='OR'), name='live_for_user_matches_status', violation_error_message='live_for_user is derived from status and cannot be set directly.'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('gateway_token__gt', ''), ('paid_until__isnull', False)), _connector='OR'), name='active_subscription_is_paid_up'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', '-received_at'], name='payments_pa_subscri_4404f1_idx'),
        ),
    ]
