"""
Django settings for cultivatorscollective project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Safe to import here: it reads an environment mapping and touches no model and
# no setting, so it does not need the app registry that this file is loaded to
# build. See its module docstring for why the reader lives there and not here.
from app.documents.storage import documents_storage_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env into the process environment for local development. In deployed
# environments set real environment variables and ship no .env file.
try:
    from dotenv import load_dotenv
except ImportError:
    pass
else:
    load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Read a boolean from the environment. Accepts 1/true/yes/on."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    """Read a comma-separated list from the environment.

    A variable that is present but empty falls back to the default. Without
    that, the blank placeholders in .env.example would silently override every
    default here.
    """
    raw = os.environ.get(name) or ''
    if not raw.strip():
        raw = default
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set. Copy .env.example to .env and fill it in, '
        'or export the variable in your environment.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default='127.0.0.1,localhost' if DEBUG else '',
)

# Needed once the site is served over HTTPS behind a proxy or on a real domain.
# The Next.js origin must appear here, otherwise its POSTs fail CSRF checks.
CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000' if DEBUG else '',
)


# Cross-origin requests from the Next.js frontend
# https://github.com/adamchainz/django-cors-headers

# Next.js runs on its own origin, so the browser treats every API call as
# cross-origin. Only the origins listed here may read responses.
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000' if DEBUG else '',
)

# Required for session-cookie auth: without it the browser sends no cookies.
CORS_ALLOW_CREDENTIALS = True

# The frontend reads this token from JavaScript and echoes it in X-CSRFToken,
# so it cannot be HttpOnly. The session cookie stays HttpOnly.
CSRF_COOKIE_HTTPONLY = False

# 'Lax' is enough while frontend and API share a parent domain in production.
# Cross-site deployment (different registrable domains) needs 'None' + HTTPS.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Cookies must never travel in cleartext outside local development.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'corsheaders',

    # Local. One app per feature; each owns its own models, admin, schemas and
    # router, and the routers are mounted in cultivatorscollective/api.py.
    'app.common',
    'app.accounts',
    'app.authn',
    'app.documents',
    'app.membership',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware so preflight responses are not redirected.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cultivatorscollective.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Used by 'manage.py runserver', which is WSGI-only in Django 6.1.
WSGI_APPLICATION = 'cultivatorscollective.wsgi.application'

# ASGI entrypoint, served by Uvicorn: cultivatorscollective.asgi:application


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Authentication: the user model
# https://docs.djangoproject.com/en/6.1/topics/auth/customizing/#substituting-a-custom-user-model

# Members and staff are the same model, told apart by is_staff. Changing this
# after the project has real data is close to impossible, which is why it is
# set from the first migration rather than deferred.
AUTH_USER_MODEL = 'accounts.User'


# Field-level encryption
# See common/crypto.py for what each of these protects and why they are separate
# from DJANGO_SECRET_KEY.

# 32 bytes, base64. Encrypts identity-document numbers at rest. Losing it makes
# every stored ID number unrecoverable; leaking it exposes all of them.
FIELD_ENCRYPTION_KEY = os.environ.get('DJANGO_FIELD_ENCRYPTION_KEY', '')

# 32 bytes, base64. Keys the searchable digests of ID numbers and email
# addresses. Changing it invalidates every stored digest, so uniqueness checks
# and "have we seen this address" lookups would need a rebuild.
BLIND_INDEX_PEPPER = os.environ.get('DJANGO_BLIND_INDEX_PEPPER', '')

if not FIELD_ENCRYPTION_KEY or not BLIND_INDEX_PEPPER:
    raise ImproperlyConfigured(
        'DJANGO_FIELD_ENCRYPTION_KEY and DJANGO_BLIND_INDEX_PEPPER must both be '
        'set. Generate each with:\n'
        '    python -c "import base64, secrets; '
        'print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())"'
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Django serves no pages of its own -- everything here is the admin's brand skin
# (see static/cc_admin/ and templates/admin/base_site.html). The cc_admin/ prefix
# keeps it clear of django.contrib.admin's own static/admin/ tree, so nothing here
# can shadow an upstream admin asset.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Only used by collectstatic. Without it the admin's stylesheets and the brand skin
# both 404 once DEBUG is off, because runserver's static handler is gone and nothing
# has written the files anywhere a web server can find them.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Club documents: where the files are stored and how they are addressed
#
# Azure Blob Storage, fronted by the CDN. Every variable behind this is read and
# validated by documents.storage.documents_storage_config, which is a pure
# function of an environment mapping -- so the refusals that matter (a CDN base
# that is not https, or whose path disagrees with the container name) are tested
# without an Azure account, and are named in one place rather than described here
# as well. See documents/models.py for what is recorded about each revision.
#
# Note that with a container configured, django-storages must be installed for
# Django to start: FileField resolves a callable storage at import. That is the
# intended failure -- immediate and named, rather than an upload that works on a
# developer's disk and dies in the admin.

# Defining STORAGES replaces Django's defaults wholesale, so 'default' and
# 'staticfiles' are restated here rather than inherited.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
    },
    # Deliberately not 'default': whatever else this project ever stores must not
    # land in the container the CDN serves to the public. Azure Blob Storage when
    # DJANGO_DOCUMENT_STORAGE_CONTAINER is set, local disk otherwise.
    'documents': documents_storage_config(os.environ, debug=DEBUG),
}

# Only reached by the filesystem fallback above. Served by runserver under
# DEBUG (see the project URLconf); a deployment with no container configured
# needs a real web server on this path.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# The address OTP emails are sent from. Django's default is 'webmaster@localhost'.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@cultivatorscollective.co.za'
)


# Cache
# https://docs.djangoproject.com/en/6.1/topics/cache/

# Rate limiting for the auth endpoints is enforced through the cache, so in
# production this must be a shared backend (Redis or Memcached). The per-process
# default below means each Uvicorn worker would count separately.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cultivatorscollective',
    }
}


# Authentication: passkeys (WebAuthn)

# The Relying Party ID is a registrable domain, never a URL and never an IP
# address. It must be the frontend's hostname or a parent of it, because the
# credential is bound to the origin the JavaScript runs on -- not to Django's.
# Locally that means signing in at http://localhost:3000, not 127.0.0.1.
WEBAUTHN_RP_ID = os.environ.get('DJANGO_WEBAUTHN_RP_ID') or (
    'localhost' if DEBUG else ''
)

WEBAUTHN_RP_NAME = os.environ.get('DJANGO_WEBAUTHN_RP_NAME', 'Cultivators Collective')

# Full origins (scheme, host, port) that may present credentials for the RP ID
# above. Normally identical to DJANGO_CORS_ALLOWED_ORIGINS.
WEBAUTHN_ORIGINS = env_list(
    'DJANGO_WEBAUTHN_ORIGINS',
    default='http://localhost:3000' if DEBUG else '',
)

# How long a generated challenge stays valid, in seconds. Kept short: it is
# held in the session between the two halves of a ceremony.
WEBAUTHN_CHALLENGE_TTL_SECONDS = 300


# Authentication: email one-time passcodes

OTP_CODE_LENGTH = 6

# Five minutes is long enough for an email to arrive and short enough that a
# leaked code is worthless by the time it is found.
OTP_TTL_SECONDS = 300

# Verification attempts against a single code before it is burned. Without this
# a six-digit code is brute-forceable.
OTP_MAX_ATTEMPTS = 5


# Throttling
# https://django-ninja.dev/guides/throttling/

# Scopes referenced by the throttle classes in authn/throttles.py. Rates are
# per client IP; the OTP send rate is the one that stops the API being used to
# mailbomb a member.
NINJA_DEFAULT_THROTTLE_RATES = {
    'auth_start': '20/m',
    'otp_start': '5/m',
    'otp_verify': '10/m',
    'passkey_verify': '20/m',
    # Tighter than the rest on purpose: a person joins a club once, and
    # nothing legitimate registers twice in a minute. See
    # membership/throttles.py -- this is the control that stands in for the
    # CSRF check an unauthenticated, server-to-server endpoint cannot have.
    'register': '5/m',
    # The nickname check the sign-up form makes when the field loses focus.
    # Looser than `register`: a member tries a few names in one sitting, and
    # each one is a request. See membership/throttles.py.
    'nickname_availability': '30/m',
}
