# Generated by Django 6.1 on 2026-09-01 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTouch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('storefront', models.CharField(choices=[('club', 'Cultivators Collective'), ('market', 'Produce market')], db_index=True, help_text='The shopfront the visitor arrived at.', max_length=16)),
                ('source', models.CharField(blank=True, help_text='utm_source — where the click came from, e.g. instagram.', max_length=200)),
                ('medium', models.CharField(blank=True, help_text='utm_medium — how it arrived, e.g. cpc, email, social.', max_length=200)),
                ('campaign', models.CharField(blank=True, help_text='utm_campaign — which campaign, e.g. spring-open-day.', max_length=200)),
                ('term', models.CharField(blank=True, help_text='utm_term — the paid keyword, where there is one.', max_length=200)),
                ('content', models.CharField(blank=True, help_text='utm_content — which creative or link within the campaign.', max_length=200)),
                ('click_network', models.CharField(blank=True, choices=[('google', 'Google Ads'), ('meta', 'Meta (Facebook, Instagram)'), ('microsoft', 'Microsoft Advertising'), ('tiktok', 'TikTok')], db_index=True, help_text='The ad network that tagged the click, where one did.', max_length=16)),
                ('click_id', models.CharField(blank=True, help_text='The network’s own id for the click — gclid, fbclid, msclkid or ttclid. What reconciles a signup against ad spend.', max_length=255)),
                ('referrer', models.CharField(blank=True, help_text='The site that linked here, as origin and path only — no query string. Blank for a direct arrival.', max_length=255)),
                ('landing_path', models.CharField(blank=True, help_text='The path on this site the visitor arrived on.', max_length=255)),
                ('seen_at', models.DateTimeField(blank=True, help_text='When the visit happened, as the browser reported it. Empty where that could not be trusted.', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'campaign touch',
                'verbose_name_plural': 'campaign touches',
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['source', 'medium', 'campaign'], name='campaign_touch_by_campaign'), models.Index(fields=['-recorded_at'], name='campaign_touch_by_recorded')],
                'constraints': [models.CheckConstraint(condition=models.Q(('storefront__in', ['club', 'market'])), name='campaign_touch_storefront_is_known', violation_error_message='That is not a storefront this platform serves.'), models.CheckConstraint(condition=models.Q(('click_network__in', ['google', 'meta', 'microsoft', 'tiktok', ''])), name='campaign_touch_click_network_is_known', violation_error_message='That is not an ad network this platform recognises.'), models.CheckConstraint(condition=models.Q(models.Q(('click_id', ''), ('click_network', '')), models.Q(models.Q(('click_network', ''), _negated=True), models.Q(('click_id', ''), _negated=True)), _connector='OR'), name='campaign_touch_click_is_a_pair', violation_error_message='A click id needs the network that issued it, and a network needs the id.'), models.CheckConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('medium', ''), _negated=True), models.Q(('campaign', ''), _negated=True), models.Q(('term', ''), _negated=True), models.Q(('content', ''), _negated=True), models.Q(('click_id', ''), _negated=True), models.Q(('referrer', ''), _negated=True), _connector='OR'), name='campaign_touch_says_something', violation_error_message='A campaign touch has to name a source, a campaign, a click or a referring site.')],
            },
        ),
    ]
