/**
 * The four profile calls the browser makes, and the shape they answer with.
 *
 * A module of its own rather than more functions in `lib/api.ts`, following `registration-api.ts`
 * and `club-documents-api.ts`: one screen's calls, in one file, so the general client stays the
 * general client.
 *
 * Everything here goes through `apiFetch`, which is what attaches the session cookie and the CSRF
 * token. The avatar upload is the exception worth reading twice — it sends `FormData` and must
 * therefore *not* set a content type, because the boundary is generated by the browser and a
 * hand-written `multipart/form-data` header omits it. `apiFetch` only sets a content type when a
 * body is present and none is set, and `FormData` counts, so the guard is that this passes no
 * header at all.
 *
 * The fifth endpoint — `GET /api/accounts/me/avatar` — has no function here. It is fetched by the
 * browser as an image, from the `avatar_url` in the payload below, so there is nothing for
 * JavaScript to do with it.
 */

import { ApiError, apiFetch, apiBaseUrl } from './api'
import type { ProfileSubmission } from './profile'

/**
 * A member's own record, mirroring `ProfileOut` in `accounts/schemas.py`.
 *
 * `id_number_masked` is all but the last four digits replaced with `*`, blank when the club holds
 * no document, and the literal `UNREADABLE` for a record that will not decrypt. The plaintext has
 * no representation here and none in the response: `accounts.profile` has no way to produce one.
 *
 * `avatar_url` is a path on the Django API, already carrying its version, or `null`. Never a
 * storage address — the avatars container is private, and the only way to a photograph is the
 * endpoint that checks the session first.
 */
export type Profile = {
  first_name: string
  last_name: string
  /** Shown, never editable here: unique across the club, so changing one is a club-facing act. */
  nickname: string
  /** Shown, never editable here: it is the sign-in identifier. */
  email: string | null
  /** `+27` and nine digits, or blank. */
  mobile: string
  display_name: string
  /** ISO date, or null. Read-only: it came off an identity document. */
  date_of_birth: string | null
  /** ISO datetime, or null when nobody has checked the date against a document. */
  date_of_birth_verified_at: string | null
  has_id_number: boolean
  id_number_masked: string
  has_avatar: boolean
  avatar_url: string | null
  role: string
  status: string
}

/** A refusal from a profile write, mirroring `ProfileRefusedOut`. */
export type ProfileRefusedBody = {
  detail: string
  /** Per-field messages, keyed by the API's field name (`first_name`, not `firstName`). */
  fields?: Record<string, string[]>
  /** True for the one refusal that is not about the value: the number belongs to someone else. */
  mobile_unavailable?: boolean
}

/**
 * The absolute address of an avatar path, for an `img` element.
 *
 * The API returns a root-relative path, and that path is not resolvable by the browser: this app is
 * served from its own origin, so a relative address resolves against Next.js and 404s there while
 * the image sits happily on Django. The same problem `documents.api._absolute_url` solves on the
 * server, solved here instead because only the browser knows it is the one asking.
 *
 * `null` in, `null` out, so a caller with no photograph renders initials rather than an `img` with
 * an empty `src` — which browsers resolve to the current page and fetch a second copy of it.
 */
export const avatarSrc = (path: string | null): string | null =>
  path === null ? null : `${apiBaseUrl()}${path}`

export const getProfile = () => apiFetch<Profile>('/api/accounts/me/profile')

/**
 * Save the three editable fields.
 *
 * A PUT carrying all three, matching the endpoint: the screen holds all three, so behaviour does
 * not depend on what this chose to omit.
 */
export const putProfile = (submission: ProfileSubmission) =>
  apiFetch<Profile>('/api/accounts/me/profile', {
    method: 'PUT',
    body: JSON.stringify(submission),
  })

/**
 * Upload a cropped photograph.
 *
 * `blob` is what the cropper's canvas produced — already square, already small. The API re-decodes
 * and re-encodes it regardless, which is not a slight on this: an endpoint that trusted its client
 * is an endpoint whose guarantees end at the first caller that is not this file.
 *
 * A POST rather than a PUT even though it replaces, because Django does not parse a multipart body
 * on PUT. See the endpoint.
 */
export const postAvatar = (blob: Blob) => {
  const form = new FormData()
  // `image` is the parameter name in `upload_avatar`. The file name is discarded server-side --
  // `avatar_upload_to` writes one path per account -- so this only has to be present.
  form.append('image', blob, 'avatar.jpg')

  return apiFetch<Profile>('/api/accounts/me/avatar', {
    method: 'POST',
    // No `Content-Type`, deliberately. The multipart boundary is generated by the browser, and a
    // header written by hand here would name a boundary that is not in the body.
    body: form,
  })
}

export const deleteAvatar = () =>
  apiFetch<Profile>('/api/accounts/me/avatar', { method: 'DELETE' })

/**
 * Whether an unknown value is a refusal body, checked field by field.
 *
 * The response is data from another process, so it is narrowed rather than asserted. A 422 whose
 * body is not the shape this expects falls through to `failed`, which shows "could not be saved
 * just now" — true, and better than reading `fields` off `undefined` and rendering nothing.
 */
const isRefusalBody = (value: unknown): value is ProfileRefusedBody =>
  typeof value === 'object' &&
  value !== null &&
  'detail' in value &&
  typeof (value as { detail: unknown }).detail === 'string'

export type SaveOutcome =
  | { readonly status: 'saved'; readonly profile: Profile }
  | { readonly status: 'refused'; readonly refusal: ProfileRefusedBody }
  | { readonly status: 'failed'; readonly reason: string }

/** The two statuses that carry a refusal the member can act on. Anything else is a failure. */
const REFUSAL_STATUSES = [409, 422] as const

/**
 * Save, and report the three outcomes the screen draws differently.
 *
 * Never throws. A form that throws leaves a member looking at a spinner, and the three cases here
 * genuinely are three screens: refusals marked up against their fields, one sentence about a
 * mobile number that belongs to somebody else, or "could not be saved just now".
 *
 * The per-field messages come off `ApiError.body`, which is why that property exists. `apiFetch`
 * throws before a caller could read the response, and the alternative — a second `fetch` here that
 * bypasses it — would be a second copy of the CSRF handling.
 */
export const saveProfile = async (submission: ProfileSubmission): Promise<SaveOutcome> => {
  try {
    return { status: 'saved', profile: await putProfile(submission) }
  } catch (caught) {
    const isRefusal =
      caught instanceof ApiError &&
      REFUSAL_STATUSES.some((status): boolean => status === caught.status)

    if (isRefusal && isRefusalBody(caught.body)) {
      return { status: 'refused', refusal: caught.body }
    }

    if (isRefusal) {
      // A refusal status with a body this does not recognise. The status still says the member can
      // act on it, so the sentence is reported rather than swallowed into "try again".
      return { status: 'refused', refusal: { detail: caught.message } }
    }

    return {
      status: 'failed',
      reason: caught instanceof Error ? caught.message : 'The club could not be reached.',
    }
  }
}
