# Generated by Django 6.1 on 2026-08-26 06:23

import app.strains.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finished_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(editable=False, max_length=40)),
                ('is_available', models.BooleanField(default=True, help_text='Clear this to stop offering the term on new strains. Existing strains keep it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('slug',), name='aroma_slug_unique', violation_error_message='That aroma is already in the list.')],
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(editable=False, max_length=40)),
                ('is_available', models.BooleanField(default=True, help_text='Clear this to stop offering the term on new strains. Existing strains keep it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('slug',), name='effect_slug_unique', violation_error_message='That effect is already in the list.')],
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('hidden', 'Hidden'), ('inactive', 'Inactive')], default='pending', max_length=16)),
                ('name', models.CharField(help_text='The name of the strain.', max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('strain_type', models.CharField(choices=[('indica', 'Indica'), ('sativa', 'Sativa'), ('hybrid', 'Hybrid')], help_text='Indica, Sativa or Hybrid.', max_length=16)),
                ('genetic_lineage', models.CharField(blank=True, help_text="Parentage as text, e.g. 'OG Kush x Durban Poison'. Not the classification -- that is Strain type.", max_length=200)),
                ('breeder_origin', models.CharField(blank=True, help_text='The breeder or origin, if known.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Shown on the generic strain page. Compliance-governed copy: describe the plant, claim nothing about what it treats.')),
                ('thc_content', models.DecimalField(blank=True, decimal_places=2, help_text='Typical THC, as a percentage. Blank if unknown.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('cbd_content', models.DecimalField(blank=True, decimal_places=2, help_text='Typical CBD, as a percentage. Blank if unknown.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('other_cannabinoids', models.JSONField(blank=True, default=dict, help_text='Minor cannabinoids as a JSON object, e.g. {"CBG": 0.8}. Display only -- not searchable.')),
                ('terpene_profile', models.JSONField(blank=True, default=dict, help_text='Terpenes as a JSON object, e.g. {"myrcene": 0.5}. Display only -- not searchable.')),
                ('disease_resistance', models.JSONField(blank=True, default=dict, help_text='Resistance to pests and diseases as a JSON object. Display only -- not searchable.')),
                ('flowering_time_weeks', models.PositiveSmallIntegerField(blank=True, help_text='Weeks in flower. Blank if unknown.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('preferred_growing_environment', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('greenhouse', 'Greenhouse')], max_length=16)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=16)),
                ('aromas', models.ManyToManyField(blank=True, help_text='One or more. A strain rarely has exactly one aroma.', related_name='strains', to='strains.aroma')),
                ('effects', models.ManyToManyField(blank=True, help_text='One or more, as members describe them.', related_name='strains', to='strains.effect')),
                ('exclusive_to', models.ForeignKey(blank=True, help_text='Leave blank for a strain any cultivator may offer. Set it to reserve the strain to one cultivator -- their own genetics, which nobody else may list against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_strains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CultivatorStrainListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('short_description', models.CharField(blank=True, help_text='One or two sentences, shown beside your name when a member compares cultivators offering this strain.', max_length=280)),
                ('description', models.TextField(blank=True, help_text='The fuller description on your own listing page.')),
                ('image', models.ImageField(blank=True, help_text='Your photograph of this strain.', upload_to=app.strains.models.listing_image_upload_to)),
                ('default_grow_price', models.DecimalField(decimal_places=2, help_text='Your standard price, in Rand, to grow one plant of this strain. Each plant you upload carries its own grow price; this is what it defaults to.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_yield_grams', models.DecimalField(decimal_places=2, help_text='The least dry weight, in grams, you undertake to deliver from one plant of this strain.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cultivator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strain_listings', to=settings.AUTH_USER_MODEL)),
                ('finished_product_types', models.ManyToManyField(blank=True, help_text='Which forms you will deliver this strain in. A plant you upload may offer these and no others.', related_name='strain_listings', to='finished_product.finishedproducttype')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='strains.strain')),
            ],
            options={
                'verbose_name': 'cultivator strain listing',
                'ordering': ('strain__name', 'default_grow_price'),
            },
        ),
        migrations.AddConstraint(
            model_name='strain',
            constraint=models.UniqueConstraint(fields=('slug',), name='strain_slug_unique', violation_error_message='A strain with that name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='strain',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'hidden', 'inactive'])), name='strain_status_is_known', violation_error_message='That is not a strain status this platform recognises.'),
        ),
        migrations.AddConstraint(
            model_name='strain',
            constraint=models.CheckConstraint(condition=models.Q(('strain_type__in', ['indica', 'sativa', 'hybrid'])), name='strain_type_is_known', violation_error_message='That is not a strain type this platform recognises.'),
        ),
        migrations.AddConstraint(
            model_name='strain',
            constraint=models.CheckConstraint(condition=models.Q(('thc_content__isnull', True), models.Q(('thc_content__gte', 0), ('thc_content__lte', Decimal('100.00'))), _connector='OR'), name='strain_thc_is_a_percentage', violation_error_message='THC must be a percentage between 0 and 100.'),
        ),
        migrations.AddConstraint(
            model_name='strain',
            constraint=models.CheckConstraint(condition=models.Q(('cbd_content__isnull', True), models.Q(('cbd_content__gte', 0), ('cbd_content__lte', Decimal('100.00'))), _connector='OR'), name='strain_cbd_is_a_percentage', violation_error_message='CBD must be a percentage between 0 and 100.'),
        ),
        migrations.AddIndex(
            model_name='cultivatorstrainlisting',
            index=models.Index(fields=['strain', 'status'], name='listing_by_strain'),
        ),
        migrations.AddIndex(
            model_name='cultivatorstrainlisting',
            index=models.Index(fields=['cultivator', 'status'], name='listing_by_cultivator'),
        ),
        migrations.AddConstraint(
            model_name='cultivatorstrainlisting',
            constraint=models.UniqueConstraint(fields=('cultivator', 'strain'), name='one_listing_per_cultivator_and_strain', violation_error_message='You already have a listing for that strain. Edit it rather than creating a second one.'),
        ),
        migrations.AddConstraint(
            model_name='cultivatorstrainlisting',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'listed', 'withdrawn'])), name='listing_status_is_known', violation_error_message='That is not a listing status this platform recognises.'),
        ),
        migrations.AddConstraint(
            model_name='cultivatorstrainlisting',
            constraint=models.CheckConstraint(condition=models.Q(('default_grow_price__gt', 0)), name='listing_grow_price_is_positive', violation_error_message='A grow price must be more than zero.'),
        ),
        migrations.AddConstraint(
            model_name='cultivatorstrainlisting',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_yield_grams__gt', 0)), name='listing_minimum_yield_is_positive', violation_error_message='A minimum yield must be more than zero.'),
        ),
        migrations.AddConstraint(
            model_name='cultivatorstrainlisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'listed'), _negated=True), models.Q(('short_description', ''), _negated=True), _connector='OR'), name='listed_listing_has_a_short_description', violation_error_message='A listed offer needs a short description -- it is what a member reads beside your name.'),
        ),
    ]
