# Generated by Django 6.1 on 2026-08-23 09:47

import django.core.validators
import django.db.models.deletion
import app.documents.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier used by the sign-up form, e.g. "constitution". Never change this on a document members have already agreed to.', max_length=60, unique=True)),
                ('title', models.CharField(help_text='What a member sees, e.g. "Constitution".', max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Low numbers first on the sign-up form.')),
                ('required_at_signup', models.BooleanField(default=True, help_text='Whether joining members must agree to this document. Untick to retire a document without touching the agreements already given.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'club document',
                'ordering': ('position', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='This revision\'s version, e.g. "2" or "2026-08". Unique per document.', max_length=32, validators=[django.core.validators.RegexValidator(message='A version label must start with a letter or digit and may contain only letters, digits, dots, dashes and underscores.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('file', models.FileField(help_text='The PDF as members will read it. Uploaded straight to the CDN.', max_length=255, storage=app.documents.storage.document_storage, upload_to=app.documents.storage.document_upload_to)),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0, editable=False)),
                ('consent_text', models.TextField(help_text='The exact sentence a member ticks, e.g. "I have read and agree to the Constitution". Recorded against every agreement.')),
                ('consent_text_sha256', models.CharField(editable=False, max_length=64)),
                ('change_note', models.TextField(blank=True, help_text='Staff-facing: what changed in this revision, and who decided it.')),
                ('requires_reacceptance', models.BooleanField(default=False, help_text='Tick when the change is material. Members who agreed to an earlier revision will be asked again; leave unticked for a typo fix.')),
                ('effective_from', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.clubdocument')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document version',
                'ordering': ('document__position', '-effective_from', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('file_sha256', models.CharField(editable=False, max_length=64)),
                ('consent_text_sha256', models.CharField(editable=False, max_length=64)),
                ('source', models.CharField(choices=[('signup', 'Sign-up'), ('reacceptance', 'Re-acceptance'), ('admin', 'Recorded by staff')], default='signup', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_consents', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'document agreement',
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'label'), name='document_version_label_unique_per_document', violation_error_message='That version label is already used for this document.'),
        ),
        migrations.AddIndex(
            model_name='documentconsent',
            index=models.Index(fields=['user', 'version'], name='documents_d_user_id_b7272a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentconsent',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='document_consent_once_per_version', violation_error_message='This member has already agreed to that revision.'),
        ),
    ]
