# Generated by Django 6.1 on 2026-08-27 10:36

import app.commerce.producers.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_name', models.CharField(help_text='What members see. The farm trades under this, not under an owner’s nickname.', max_length=80)),
                ('trading_name_key', models.CharField(editable=False, max_length=80)),
                ('public_description', models.TextField(blank=True, help_text='Your description of your farm, shown to members. Compliance-governed copy: no claim about what cannabis does.')),
                ('image', models.ImageField(blank=True, help_text='One photograph, shown beside your name.', upload_to=app.commerce.producers.models.profile_image_upload_to)),
                ('is_published', models.BooleanField(default=False, help_text='Members see this profile only once it is published.')),
                ('collection_address', models.TextField(blank=True, help_text='Where a courier collects from. Members never see this.')),
                ('bank_account_name', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('bank_branch_code', models.CharField(blank=True, max_length=16)),
                ('bank_account_number_encrypted', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'producer',
                'ordering': ('trading_name',),
                'constraints': [models.UniqueConstraint(fields=('trading_name_key',), name='producer_trading_name_key_unique', violation_error_message='A producer already trades under that name.'), models.CheckConstraint(condition=models.Q(('trading_name_key', django.db.models.functions.text.Lower('trading_name'))), name='producer_trading_name_key_matches_name', violation_error_message='trading_name_key is derived from trading_name and cannot be set directly.')],
            },
        ),
        migrations.CreateModel(
            name='ProducerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('full', 'Appointed staff, full rights'), ('limited', 'Appointed staff, limited rights')], db_index=True, default='limited', max_length=16)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_for_producer', models.UUIDField(blank=True, editable=False, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='producers.producer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'producer appointment',
                'ordering': ('producer', 'role', 'appointed_at'),
                'constraints': [models.UniqueConstraint(fields=('producer', 'user'), name='producer_membership_once_per_producer', violation_error_message='This person is already appointed to that producer.'), models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'full', 'limited'])), name='producer_membership_role_is_known', violation_error_message='That is not a producer role this platform recognises.'), models.UniqueConstraint(fields=('primary_for_producer',), name='producer_membership_one_primary', violation_error_message='That producer already has a primary cultivator.'), models.CheckConstraint(condition=models.Q(models.Q(('primary_for_producer__isnull', False), ('role', 'primary')), models.Q(models.Q(('role', 'primary'), _negated=True), ('primary_for_producer__isnull', True)), _connector='OR'), name='producer_membership_primary_slot_matches_role', violation_error_message='primary_for_producer is derived from role and cannot be set directly.')],
            },
        ),
        migrations.CreateModel(
            name='ProducerStorefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('storefront', models.CharField(choices=[('club', 'Cultivators Collective'), ('market', 'Produce market')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefronts', to='producers.producer')),
            ],
            options={
                'verbose_name': 'producer storefront',
                'ordering': ('producer', 'storefront'),
                'constraints': [models.UniqueConstraint(fields=('producer', 'storefront'), name='producer_storefront_once_each', violation_error_message='This producer already sells into that storefront.'), models.CheckConstraint(condition=models.Q(('storefront__in', ['club', 'market'])), name='producer_storefront_is_known', violation_error_message='That is not a storefront this platform serves.')],
            },
        ),
    ]
